# Generated by Django 3.0 on 2023-03-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='rates',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
