# Generated by Django 3.0 on 2023-03-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230309_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation2',
            name='restaurantId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Restaurants'),
        ),
    ]
