# Generated by Django 3.0 on 2023-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reservation2_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('image_url', models.CharField(max_length=500, null=True)),
                ('rate', models.ManyToManyField(to='api.Rates')),
            ],
        ),
    ]
