# Generated by Django 3.0 on 2023-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_barbershop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('image_url', models.CharField(max_length=500, null=True)),
                ('time', models.TimeField()),
                ('rate', models.ManyToManyField(to='api.Rates')),
            ],
        ),
    ]
