# Generated by Django 3.0 on 2023-03-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationBarber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=20, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('comment', models.CharField(max_length=150, null=True)),
                ('choose_specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Specialist')),
                ('restaurantId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Restaurants')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
