# Generated by Django 3.0 on 2023-03-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_reservationbarber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationbarber',
            name='restaurantId',
        ),
        migrations.AddField(
            model_name='reservationbarber',
            name='barberId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Barbershop'),
        ),
    ]
