# Generated by Django 3.0 on 2023-03-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20230311_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation2',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='duration',
        ),
        migrations.AddField(
            model_name='reservation2',
            name='barberId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Barbershop'),
        ),
        migrations.AddField(
            model_name='reservation2',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation2',
            name='party_size',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ReservationBarber',
        ),
    ]
