# Generated by Django 3.0 on 2023-03-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20230312_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='rate',
        ),
    ]
