# Generated by Django 3.0 on 2023-03-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20230312_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='general_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='general_rate',
            field=models.IntegerField(null=True),
        ),
    ]
