# Generated by Django 3.0 on 2023-03-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20230312_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='barbers',
            field=models.ManyToManyField(to='api.Barbershop'),
        ),
        migrations.AddField(
            model_name='categories',
            name='restaurants',
            field=models.ManyToManyField(to='api.Restaurants'),
        ),
    ]
