# Generated by Django 3.0 on 2023-03-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_reservation2_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation2',
            name='barber',
            field=models.ManyToManyField(to='api.Barbershop'),
        ),
    ]
