# Generated by Django 3.0 on 2023-03-16 11:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_reservation2_barber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='type',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='api_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
