# Generated by Django 3.0 on 2023-03-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20230316_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation2',
            name='userId',
        ),
    ]
