# Generated by Django 3.0 on 2023-03-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_reservation2_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='userId',
        ),
    ]
