# Generated by Django 3.0 on 2023-03-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20230317_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='party_size',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='time',
        ),
       migrations.AddField(
           model_name='reservation2',
            name='booking',
            field=models.ManyToManyField(to='api.Booking'),
        ),
    ]
