# Generated by Django 3.0 on 2023-03-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20230322_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation2',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='reservation2',
            name='booking',
        ),
        migrations.AddField(
            model_name='reservation2',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Booking'),
        ),
    ]
