# Generated by Django 3.0 on 2023-03-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20230322_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation2',
            name='booking',
        ),
    ]
