# Generated by Django 3.0 on 2023-03-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_reservation2_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation2',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Booking'),
        ),
    ]
